### ISSUE TITLE
moonlight / nightmode

### ISSUE THREAD

**Issue by netdoggy** [al-one/hass-miio-yeelink#12]
Greetings!
Is there a way to turn on / off the moonlight mode for the Ceiling light in HomeAssist? I tried to figure it out but it didn't work out for me

**Comment by LLInH9rA** [comment]
#configuration.yaml
input_boolean:
  yeelink_nightlight:
    name: nightlight
    icon: mdi:lightbulb

#automations.yaml
- alias: Nightlight Off
  trigger:
  - platform: state
    entity_id: input_boolean.yeelink_nightlight
    to: "off"
  action:
    - service: miio_yeelink.send_command
      data:
        entity_id: light.xiaomi_yeelink
        method: set_ps
        params:
        - nightlight
        - 'off'

- alias: Nightlight On
  trigger:
  - platform: state
    entity_id: input_boolean.yeelink_nightlight
    to: "on"
  action:
    - service: miio_yeelink.send_command
      data:
        entity_id: light.xiaomi_yeelink
        method: set_ps
        params:
        - nightlight
        - 'on'

**Comment by netdoggy** [comment]
Cool! Thank you. it works
