### ISSUE TITLE
Turn_on with color attributes have no effect on color

### ISSUE THREAD

**Issue by CODeRUS** [al-one/hass-miio-yeelink#13]
calling light.turn_on command with color parameters only turning it on with previous assigned color. calling it again changes color to desired one.

**Comment by matteos1** [comment]
no changes of color yeelink.light.bslamp2
da yeelink
Firmware: 2.0.6_0041

**Comment by al-one** [comment]
@CODeRUS Try last commit: https://github.com/al-one/hass-miio-yeelink/commit/c31d2e527a67865d7b42ff3ac4c60779de21071c of [master](https://github.com/al-one/hass-miio-yeelink/tree/master).

**Comment by CODeRUS** [comment]
thanks, works better. now it starts to light with previous color and change color to desired one in transition :)
