### ISSUE TITLE
Working with YLDP25YL/YLDP26YL M2 globe?

### ISSUE THREAD

**Issue by richardfoong** [al-one/hass-miio-yeelink#25]
Was looking at getting this newer slim line globe from yeelight but wasn't quite sure if its working with the integration. 

https://www.aliexpress.com/item/1005002095491166.html

**Comment by al-one** [comment]
Can they be bound by [Mi Home](https://apps.apple.com/us/app/id957323480) APP? If possible, tell me their product name or model (eg: yeelink.light.xxxx) in Mi Home.

**Comment by al-one** [comment]
The devices of these two models are connected by mesh and cannot be integrated in the LAN. You can use the [hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot) component to integrate through the Xiaomi account in cloud.

**Comment by richardfoong** [comment]
Ok great thanks for the reply. Food for thought!
