### ISSUE TITLE
yeelink.light.color5 works too, can be added to "devices tested by community"

### ISSUE THREAD

**Issue by piotrdzz** [al-one/hass-miio-yeelink#26]
Hello,
yeelink.light.color5 integration via mii (token) works fine. 
official HASS Yeelight integration does not work correctly with this bulb (control over LAN with dev mode enabled) so this repository saves the hassle :)

**Comment by al-one** [comment]
👍 Thanks !

**Comment by Musickiller** [comment]
@al-one for me, it seems that the range of light temperature is cut quite a lot at the lower end (red is yellow)

**Comment by bycream** [comment]
any news yeelink.light.color3 it does not working with HA
