### ISSUE TITLE
python-miio version

### ISSUE THREAD

**Issue by rotrials** [al-one/hass-miio-yeelink#37]
Hello,

Could you please update the python-miio to the latest version? 

python-miio  is used for other custom components also. Could be that "miio_yeelink" forced the force the xiaomi miio (https://www.home-assistant.io/integrations/xiaomi_miio) to downgrade the python-miio version, which will generate some errors. Would be nice if you could update it also. 

I'm referring to the the following code from manifest.json:

  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.6"

If my understand is right it should be:

  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.9.2"

Thanks.

**Comment by al-one** [comment]
In order to be compatible with more versions of HA, I can't do this. Maybe you can upgrade it manually via pip.

**Comment by rotrials** [comment]
Ok, I thought it should be compatible with latest HA version, not all. hass-miio-yeelink ​can downgrade the python-miio.
I don't know other users, setup. But on my setup I have 2 integrations which uses the latest python-miio and hass-miio-yeelink is the only one which it's not using the latest one. 
I have upgraded it through pip, but I don't know if your integration will still work or it will try to downgrade... 
Anyway, you can close the issue. Thanks
