### ISSUE TITLE
灯具色温显示不正常

### ISSUE THREAD

**Issue by zhtengw** [al-one/hass-miio-yeelink#4]
您好，添加了几个灯具，色温显示都不正常，在HA中色温数值与拉动条是相反的，在iOS Home中色温只显示为全黑。请问这是什么原因？
![Snipaste_2021-01-11_23-04-49](https://user-images.githubusercontent.com/3148769/104199136-06a5f600-5462-11eb-84c7-4b128efa7db0.png)
![IMG_3281](https://user-images.githubusercontent.com/3148769/104199143-073e8c80-5462-11eb-8926-ec27ff773ed2.PNG)
![IMG_3282](https://user-images.githubusercontent.com/3148769/104199151-09085000-5462-11eb-8e6e-15ed381d06f5.PNG)

**Comment by al-one** [comment]
您添加的灯具型号有那些？

**Comment by zhtengw** [comment]
你好，是以下几款灯：
米家客厅吸顶灯 | MJXDD02YL | yeelink.light.ceiling21
米家卧室吸顶灯450 | MJXDD01SYL | yeelink.light.ceiling22
米家卧室吸顶灯350 | MJXDD03YL | yeelink.light.ceiling23
Yeelight逸扬直流变频风扇吊灯C900 | YLFD002/YLFD008 | yeelink.light.fancl5

**Comment by al-one** [comment]
色温相反的问题在 [v0.1.6](https://github.com/al-one/hass-miio-yeelink/releases/latest) 修复了，iOS Home中的色温问题你可以更新插件版本后再试下。

**Comment by zhtengw** [comment]
非常感谢，现在HA和iOS Home中都正常了。
