### ISSUE TITLE
Support for yeelink-light-color7.

### ISSUE THREAD

**Issue by apoorv569** [al-one/hass-miio-yeelink#40]
I just bought a `Mi LED Smart Color Bulb (B22)` and want to connect it to my `Home Assistant` server. While looking around the internet I found this repository. I see there are quiet a few supported devices here but not the `yeelink-light-color7`. Can this device work with `Home Assistant` ?

**Comment by al-one** [comment]
Maybe you can try this custom component: [hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot).

**Comment by apoorv569** [comment]
> Maybe you can try this custom component: [hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot).

Thank you this worked for me. The local method did not work, but the Online cloud method worked.
