### ISSUE TITLE
Integration fails to load since update 2024.2

### ISSUE THREAD

**Issue by Boto11** [al-one/hass-miio-yeelink#80]
Hello,

Since I updated to version 2024.2, the miio-yeelink integration fails to load properly. 
Here are the logs I'm receiving:
![logs](https://github.com/al-one/hass-miio-yeelink/assets/108519787/e17b9805-b9bf-491d-be99-2638bdc6501f)

Has anyone else encountered this issue, or am I the only one ?

**Comment by Boto11** [comment]
Release 2024.2.1 fix the issue

**Comment by olegborushko** [comment]
У меня после обновления на версию 2024.2.1 такая же проблема
