### ISSUE TITLE
yeelink.bhf_light.v2: manage heater

### ISSUE THREAD

**Issue by fcarsana** [al-one/hass-miio-yeelink#9]
Can I control yeelink.bhf_light.v2 heater?
It seems not: the only 2 entities are light and fan.

In case is not supported I found the protocol to be used to control that.
You can find it here: https://github.com/rytilahti/python-miio/issues/702

Thank you.

**Comment by al-one** [comment]
This model supports well.
You can re integrate it use HA GUI.
![yeelink.bhf_light.v2](https://user-images.githubusercontent.com/4549099/104683506-02aff780-5732-11eb-9de8-10d9fbe41ddd.png)

**Comment by fcarsana** [comment]
I did not set the model (yeelink.bhf_light.v2) during the auto discovery.
Inserting the model number it works.

Thank you!
